### ISSUE TITLE
ImportError: No module named enum/IntEnum after pip install pyone on CentOS7

### ISSUE THREAD

**Issue by marcindulak** [OpenNebula/addon-pyone#16]
https://github.com/OpenNebula/addon-pyone/commit/fb2d4b74595ebcc49eb6fb81212dbb54cdb4ee2b

```
(venv)[root@frontend ~]# python -c "import pyone"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/venv/lib/python2.7/site-packages/pyone/__init__.py", line 15, in <module>
    from pyone import bindings
  File "/root/venv/lib/python2.7/site-packages/pyone/bindings/__init__.py", line 27, in <module>
    from pyone.util import TemplatedType
  File "/root/venv/lib/python2.7/site-packages/pyone/util.py", line 20, in <module>
    from enum import IntEnum
ImportError: No module named enum
```

To fix:

```
pip install enum34
```

**Comment by marcindulak** [comment]
I was testing a wrong branch.
