### ISSUE TITLE
Unable to authenticate. 

### ISSUE THREAD

**Issue by michaelluich** [OpenNebula/addon-pyone#23]
I can't figure out why my systems give me a 401 error code. Nothing in the log to indicate why. I verified the username password.  There isn't yet and documentation I can find to help.

```
import pyone
one = pyone.OneServer("http://10.97.200.5:9869", session="oneadmin:*#*#*#*")

hostpool = one.hostpool.info()
host = hostpool.HOST[0]
id = host.ID

```
error's out with:
```
Traceback (most recent call last):
  File "/Users/michaelluich/PycharmProjects/ON_EDU/python/test1.py", line 19, in <module>
    hostpool = one.hostpool.info()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/Users/michaelluich/PycharmProjects/ON_EDU/venv/lib/python3.6/site-packages/pyone/__init__.py", line 188, in _ServerProxy__request
    ret = self._do_request("one."+methodname,self._cast_parms(params))
  File "/Users/michaelluich/PycharmProjects/ON_EDU/venv/lib/python3.6/site-packages/pyone/__init__.py", line 193, in _do_request
    return xmlrpc.client.ServerProxy._ServerProxy__request(self, method, params)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xmlrpc/client.py", line 1187, in single_request
    dict(resp.getheaders())
xmlrpc.client.ProtocolError: <ProtocolError for 10.97.200.5:9869/RPC2: 401 Unauthorized>
```

**Comment by rvalle** [comment]
I think you're not using the right URL.

you need the Xmlrpc endpoint  which I believe finishes in /RPC2. It is listed in the configuration file of OpenNebula

You might also have a reverse proxy setup

**Comment by michaelluich** [comment]
Adding /RPC2 gives the same error. 

There is no proxy between me and the server. It's just Sunstone on it's default port.

I do see the connection on the server

Thu May 10 18:55:25 2018 [I]: 192.168.229.252 - - [10/May/2018:18:55:25 +0000] "POST /RPC2 HTTP/1.1" 401 - 0.0006
Thu May 10 18:56:05 2018 [I]: 192.168.229.252 - - [10/May/2018:18:56:05 +0000] "POST /RPC2 HTTP/1.1" 401 - 0.0007
Thu May 10 19:43:06 2018 [I]: 192.168.229.252 - - [10/May/2018:19:43:06 +0000] "POST /RPC2 HTTP/1.1" 401 - 0.0006

```
one = pyone.OneServer("http://10.97.200.5:9869/RPC2", session="oneadmin:*=*=*=")
xmlrpc.client.ProtocolError: <ProtocolError for 10.97.200.5:9869/RPC2: 401 Unauthorized>
```

**Comment by michaelluich** [comment]
Your comment about finding it in the conf gave me the answer. I was trying to connect on the sunstone port(9869). NOT the XMLRPC port 2633.
```
one = pyone.OneServer("http://10.97.200.5:2633/RPC2", session="oneadmin:*=*=*=)
```
Works correctly. 
Thanks.

**Comment by rvalle** [comment]
I think you're not the first one falling into this issue.

I will see if I can detect that condition and throw a better exception or something
