### ISSUE TITLE
XML parsing errors (How to get all the VM ?)

### ISSUE THREAD

**Issue by Madko** [OpenNebula/addon-pyone#6]
Hi,

I'm trying pyone, and I'm not yet familiar with opennebula XML RPC API so maybe I'm doing something wrong. I'm using the doc for listing hosts from hostpool and it works perfectly. But when I try to do the same to get all the VM it's not working:
```
Traceback (most recent call last):
  File "./test.py", line 7, in <module>
    vmpool = one.vmpool.info(-3,-1,-1,-1)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/home/edouard.bourguignon/Documents/py2one-virtualenv/lib/python2.7/site-packages/pyone/__init__.py", line 86, in _ServerProxy__request
    return self.__response(ret)
  File "/home/edouard.bourguignon/Documents/py2one-virtualenv/lib/python2.7/site-packages/pyone/__init__.py", line 103, in __response
    nsDom = dom.parseString(nsXml)
  File "/usr/lib64/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 11912: ordinal not in range(128)
```

seems to be related to xml dom lib. Could you let me know if I'm doing it right:
```
#!/usr/bin/env python
# coding: utf-8

import pyone
one = pyone.OneServer("http://one.lab:2633/RPC2", session="ONEUSER:PASS" )

vmpool = one.vmpool.info(-3,-1,-1,-1)
```

best regards,
Edouard

**Comment by rvalle** [comment]
The error you are getting does not seem to be very legible.  Which is a problem in itself.

I have added an integration test, and the vmpool.info call seems to be working in my environment too.

Can you send me information about your environment? maybe a pip freeze. I will try to reproduce the problem.

You also mention that other calls are working, while this one in particular fails. Since the error is also an XML error parsing, I wonder whether there is something wrong with the particular XML being returned.

**Comment by Madko** [comment]
Here is my pip freeze:

```
dicttoxml==1.7.4
pyone==1.0.5
PyXB==1.2.6
xmltodict==0.11.0

```
Had to manually add xmltodict, not sure if it's normal. I'm trying to get the XML

**Comment by Madko** [comment]
So it's seems that pyone doesn't like utf8. I've got VM with characters like "à" (or other french stuffs)

so in /pyone/__init__.py, line 223, I change
`doc = dom.parseString(ret)`
to
`doc = dom.parseString(u"{0}".format(ret).encode("utf-8"))`
At least it doesn't crash anymore on unicode characters but now I have this error:
```
Traceback (most recent call last):
  File "./test.py", line 11, in <module>
    vmpool = one.vmpool.info(-3,-1,-1,-1)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/home/edouard/Documents/dev/pyone-virtualenv/lib/python2.7/site-packages/pyone/__init__.py", line 93, in _ServerProxy__request
    return self.__response(ret)
  File "/home/edouard/Documents/dev/pyone-virtualenv/lib/python2.7/site-packages/pyone/__init__.py", line 114, in __response
    return bindings.CreateFromDocument(doc.toxml())
  File "/home/edouard/Documents/dev/pyone-virtualenv/lib/python2.7/site-packages/pyone/bindings/__init__.py", line 65, in CreateFromDocument
    saxer.parse(io.BytesIO(xmld))
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/edouard/Documents/dev/pyone-virtualenv/lib/python2.7/site-packages/pyxb/binding/saxer.py", line 388, in endElementNS
    binding_object = this_state.endBindingElement()
  File "/home/edouard/Documents/dev/pyone-virtualenv/lib/python2.7/site-packages/pyxb/binding/saxer.py", line 238, in endBindingElement
    _location=info.location)
  File "/home/edouard/Documents/dev/pyone-virtualenv/lib/python2.7/site-packages/pyxb/binding/basis.py", line 2567, in append
    raise pyxb.UnrecognizedContentError(self, self.__automatonConfiguration, value, location)
pyxb.exceptions_.UnrecognizedContentError: Invalid content {http://opennebula.org/XMLSchema}RESCHED at <unknown>[22:2] (expect {http://opennebula.org/XMLSchema}PREV_STATE)
```

Thanks for helping me

**Comment by rvalle** [comment]
Yes, that makes sense to me.

The problem we have is that the XMLRPC server in Open Nebula sends what I call naked XML.

Neither xml declaration, that should include the character encoding, nor namespace declaration.

I guess that is causing the trouble. We can perhaps force it at parsing time as you do.

**Comment by rvalle** [comment]
As for the second exception looks like if you got XML that doesn't match the XSD.

Which Opennebula version do you use?

Would be great if you could capture the offending xml

**Comment by Madko** [comment]
I'm using OpenNebula 5.4.7.
The offending XML starts with <?xml version="1.0" encoding="UTF-8"?>
I don't find any information about dtd/xsd etc but I don't know much about XML. Where is the XSD ? Is it possible that it's out of date ? but the RESCHED state is quite old in OpenNebula ?

**Comment by Madko** [comment]
New errors when getting specific VM
```
Traceback (most recent call last):
  File "./test.py", line 14, in <module>
    vm = one.vm.info(x)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/home/edouard/Documents/dev/pyone-virtualenv/lib/python2.7/site-packages/pyone/__init__.py", line 93, in _ServerProxy__request
    return self.__response(ret)
  File "/home/edouard/Documents/dev/pyone-virtualenv/lib/python2.7/site-packages/pyone/__init__.py", line 114, in __response
    return bindings.CreateFromDocument(doc.toxml())
  File "/home/edouard/Documents/dev/pyone-virtualenv/lib/python2.7/site-packages/pyone/bindings/__init__.py", line 65, in CreateFromDocument
    saxer.parse(io.BytesIO(xmld))
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/edouard/Documents/dev/pyone-virtualenv/lib/python2.7/site-packages/pyxb/binding/saxer.py", line 388, in endElementNS
    binding_object = this_state.endBindingElement()
  File "/home/edouard/Documents/dev/pyone-virtualenv/lib/python2.7/site-packages/pyxb/binding/saxer.py", line 238, in endBindingElement
    _location=info.location)
  File "/home/edouard/Documents/dev/pyone-virtualenv/lib/python2.7/site-packages/pyxb/binding/basis.py", line 2588, in append
    raise pyxb.MixedContentError(self, value, location)
pyxb.exceptions_.MixedContentError: Invalid non-element content at <unknown>[2:3544]

```
The offending XML is here:
https://paste.fedoraproject.org/paste/USrj8Z1fUkWXBZx0S4t3kg

It's a very small VM (a vrouter). Nothing special.

And I also have this one, more about XML validation:
```
Traceback (most recent call last):
  File "./test.py", line 14, in <module>
    vm = one.vm.info(x)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/home/edouard/Documents/dev/pyone-virtualenv/lib/python2.7/site-packages/pyone/__init__.py", line 93, in _ServerProxy__request
    return self.__response(ret)
  File "/home/edouard/Documents/dev/pyone-virtualenv/lib/python2.7/site-packages/pyone/__init__.py", line 114, in __response
    return bindings.CreateFromDocument(doc.toxml())
  File "/home/edouard/Documents/dev/pyone-virtualenv/lib/python2.7/site-packages/pyone/bindings/__init__.py", line 65, in CreateFromDocument
    saxer.parse(io.BytesIO(xmld))
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/edouard/Documents/dev/pyone-virtualenv/lib/python2.7/site-packages/pyxb/binding/saxer.py", line 388, in endElementNS
    binding_object = this_state.endBindingElement()
  File "/home/edouard/Documents/dev/pyone-virtualenv/lib/python2.7/site-packages/pyxb/binding/saxer.py", line 238, in endBindingElement
    _location=info.location)
  File "/home/edouard/Documents/dev/pyone-virtualenv/lib/python2.7/site-packages/pyxb/binding/basis.py", line 2567, in append
    raise pyxb.UnrecognizedContentError(self, self.__automatonConfiguration, value, location)
pyxb.exceptions_.UnrecognizedContentError: Invalid content ALLOW_ORPHANS at <unknown>[2:9402] (expect {http://opennebula.org/XMLSchema}DISK_ID)

```
The offending XML for this one is here:
https://paste.fedoraproject.org/paste/cmOToaJ02WBZKLB-APULWQ

**Comment by rvalle** [comment]
The XSD files are distributed with OpenNebula, they are included in pyone and used to generate the bindings.

There are several possibilities:
* XSD files are out of date
* OpenNebula generates content that does not comply with the XSD
* PyXB cannot parse XML that is should be parsed because it is valid.

With the "ofending XML" and the XSD files we can parse and test it, then find out more. It is the same thing that OpenNebula team does, there are tests with the XSD files to check if they parse XML samples.

**Comment by rvalle** [comment]
@Madko can you test latest version 1.0.7 and see if you see improvement?
I have included a couple of fixes for utf8 chars.
I am also interested in seeing if the XSD errors still come up

**Comment by rvalle** [comment]
@Madko I have been digging deeper in the ALLOW_ORPHANS sample that you provided.
I can reproduce the code thanks to the offending xml that you provided

The beautified XML can be found here: https://pastebin.com/EKJj5XjH
The offending element is in line 475

The XSD for the VM type in version 5.4.7 is this one: https://github.com/OpenNebula/one/blob/release-5.4.7/share/doc/xsd/vm.xsd

I cannot see any ALLOW_ORPHANS element in the SNAPSHOTS section.

I think it loos like OpenNebula is generating non-compliant XML with the provided XSDs.

**Comment by Madko** [comment]
I've upgraded to 1.0.7 and no more utf8 errors. This is great. 
I'm still having the same issue when trying to get the vmpool info. And of course this particular VM with the ALLOW_ORPHANS.

With this quick and dirty hack
```
--- /home/edouard/Documents/dev/pyone-virtualenv/lib/python2.7/site-packages/pyone/__init__.py.ori	2018-03-05 08:47:42.531818899 +0100
+++ /home/edouard/Documents/dev/pyone-virtualenv/lib/python2.7/site-packages/pyone/__init__.py	2018-03-05 08:46:26.277867537 +0100
@@ -111,7 +111,10 @@
                     doc = dom.parseString(u"{0}".format(ret).encode("utf-8"))
                     doc.documentElement.setAttribute('xmlns', 'http://opennebula.org/XMLSchema')
                     # toDOM and CD_DATA is broken in PyXB until 1.2.7, so, will force SAX parsing
-		    return bindings.CreateFromDocument(doc.toxml())
+                    try:
+                        return bindings.CreateFromDocument(doc.toxml())
+                    except: 
+                        print("invalid XML")
             return ret;
 
         else:
```
I'm now able to get the vmpool info or to print my vms data without crashing. Of course I get an "invalid XML" for my offending VMs. I know it's not the proper way to deal with this kind of error but now I can go further on my pyone testings.

Should I open a bug report for the non-compliant XML with the provided XSD ?

**Comment by rvalle** [comment]
Yes, please, open the issue. 
If you can find more instances is good. You reported another related to the RESCHED element.

Meanwhile I will provide a test case were we can test XMLs that we find problematic. Maybe testing all XMLs in a directory or something similar...

**Comment by Madko** [comment]
I have maybe 10 invalid XML on 600 VM definitions, not so bad. I will provide some more XML soon.

**Comment by rvalle** [comment]
That is very good. I have a very limited testing environment. Just a couple of hosts and 3,4 VMs in vagrant.
It you can get the XML samples, I will turn them into test cases.

**Comment by Madko** [comment]
So here are some other invalid XML:
https://da.gd/nBRB
https://da.gd/nbeJ
https://da.gd/ZPgs
https://da.gd/DULD
https://da.gd/rao6Y
Only 5 out of 622 are invalid. I will see if I can grab some more on an other testing environment.

**Comment by rvalle** [comment]
Maybe it's good idea to test with other object types..

Networks, hosts, templates.... If you have a good sample size.

**Comment by rvalle** [comment]
I have now created test case 6, with a directory where failing XMLs can be included, so that we can better track them getting fixed.
they are here: https://github.com/OpenNebula/addon-pyone/tree/master/tests/ci/test_issue_006_data

From the samples you found I got:

- with international characters (now fixed)
- ALLOW_ORPHANS error on VMs (XSD issue)
- MixedContentError no idea what is it yet.

See if you can find more failing samples with different errors, that really helps!

**Comment by Madko** [comment]
A new sample of failing VM definition https://paste.fedoraproject.org/paste/UlOAoPjSWqquPckFcexbcQ

**Comment by Madko** [comment]
Not sure if it is useful to have an other one about the ALLOW_ORPHANS error: https://paste.fedoraproject.org/paste/-Y2gL0rddlGsdnGUvqKYfw

**Comment by Madko** [comment]
I've tried to iterate on hostpool and I don't have any error. But when I try to get vnpool.info:
```
Traceback (most recent call last):
  File "./test.py", line 16, in <module>
    vnetpool = one.vnpool.info(-3,-1,-1,-1)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/home/edouard.bourguignon/Documents/py2one-virtualenv/lib/python2.7/site-packages/pyone/__init__.py", line 94, in _ServerProxy__request
    return self.__response(ret)
  File "/home/edouard.bourguignon/Documents/py2one-virtualenv/lib/python2.7/site-packages/pyone/__init__.py", line 114, in __response
    return bindings.CreateFromDocument(doc.toxml())
  File "/home/edouard.bourguignon/Documents/py2one-virtualenv/lib/python2.7/site-packages/pyone/bindings/__init__.py", line 65, in CreateFromDocument
    saxer.parse(io.BytesIO(xmld))
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib64/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib64/python2.7/xml/sax/expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/edouard.bourguignon/Documents/py2one-virtualenv/lib/python2.7/site-packages/pyxb/binding/saxer.py", line 388, in endElementNS
    binding_object = this_state.endBindingElement()
  File "/home/edouard.bourguignon/Documents/py2one-virtualenv/lib/python2.7/site-packages/pyxb/binding/saxer.py", line 238, in endBindingElement
    _location=info.location)
  File "/home/edouard.bourguignon/Documents/py2one-virtualenv/lib/python2.7/site-packages/pyxb/binding/basis.py", line 2567, in append
    raise pyxb.UnrecognizedContentError(self, self.__automatonConfiguration, value, location)
pyxb.exceptions_.UnrecognizedContentError: Invalid content GATEWAY at <unknown>[1:6396] (expect {http://opennebula.org/XMLSchema}GLOBAL_PREFIX or {http://opennebula.org/XMLSchema}IP or {http://opennebula.org/XMLSchema}MAC)
```
Don't know how to get the XML for this one. I will try to get each vnet individually.

**Comment by Madko** [comment]
I have a lot of error concerning vnet.
https://paste.fedoraproject.org/paste/MG26m7Adm4Kf8LdxPyjDqw
pyxb.exceptions_.MixedContentError: Invalid non-element content at <unknown>[1:742]

**Comment by Madko** [comment]
Oh I've just the vnet definition with the Invalid content GATEWAY at <unknown>[1:912] (expect {http://opennebula.org/XMLSchema}GLOBAL_PREFIX or {http://opennebula.org/XMLSchema}IP or {http://opennebula.org/XMLSchema}MAC)
https://paste.fedoraproject.org/paste/x2HqRZAmTf5BtflTOJdxsg

**Comment by rvalle** [comment]
Thanks! very good catches. I have added them to the test case.

I am now suspecting that we also deal with an issue of PyXB, the mixed content error happens in templates (marked as XSD anyType) which does not makes sense. I think there is a bug when anyTypes contain elements with names related to other XSD elements.

Also, I could not understand why cannot you produce an XML sample related to the vnpool.info()? How are you getting the other ones? what is different? Let me know if I can help.

**Comment by Madko** [comment]
I'm getting the other XML with opennebula CLI (onevnet show ID --xml). I will do some curl to get the XML of the vnpool.info() or is there any other easier way you could think of ? Is it just onevnet list --xml ? I forget to try this one...

**Comment by rvalle** [comment]
@Madko I thought you were debugging the pyone code, and capturing the XML when it arrives. 
That would be at the same place where you suggested the UTF8 patch, I think.

**Comment by marcindulak** [comment]
I've not experienced any of these exceptions, but my opennebula is just small virtual setup.

```
cat /etc/redhat-release
# CentOS Linux release 7.4.1708 (Core)
rpm -q opennebula
# opennebula-5.4.6-1.x86_64

yum -y install python-virtualenv python34-virtualenv
yum -y install python2-future

mkdir ~/py27&& cd ~/py27
git clone https://github.com/OpenNebula/addon-pyone
virtualenv-2.7 pyone
cd pyone
. bin/activate
pip install --upgrade pip
pip --version  # 9.0.2
pip install -r ../addon-pyone/requirements.txt
cd ../addon-pyone
git rev-parse master
# b1011c320bbe37970931c8cddd44bb3dfd84fa04
make

PYTHONPATH=~/py27/addon-pyone python -c 'import pyone; one = pyone.OneServer("http://one.lab:2633/RPC2", session="ONEUSER:PASS"); one.vmpool.info(-3,-1,-1,-1)'

pip list
#dicttoxml (1.7.4)
#future (0.16.0)
#pip (9.0.2)
#PyXB (1.2.6)
#setuptools (0.9.8)
#six (1.10.0)
#xmltodict (0.11.0)
python --version  # Python 2.7.5

deactivate

mkdir ~/py34&& cd ~/py34
git clone https://github.com/OpenNebula/addon-pyone
virtualenv-3.4 pyone
cd pyone
. bin/activate
pip install --upgrade pip
pip --version  # 9.0.2
pip install -r ../addon-pyone/requirements.txt
cd ../addon-pyone
git rev-parse master
# b1011c320bbe37970931c8cddd44bb3dfd84fa04
make

PYTHONPATH=~/py34/addon-pyone python -c 'import pyone; one = pyone.OneServer("http://one.lab:2633/RPC2", session="ONEUSER:PASS"); one.vmpool.info(-3,-1,-1,-1)'

python --version  # Python 3.4.5

deactivate
```

**Comment by rvalle** [comment]
@marcindulak same for me. I have a cluster in vagrant where I can develop.
Thanks to @Madko, who has a huge environment I have now a clear understanding of where XML errors come from.

- in some cases there are missing XML elements in the XSDs as distributed by OpenNebula
- PyXB fails when there is a template element that matches an element defined in other schema. This is a problem with pyone setup, that merges all schemas into one. We will have to deal with one schema for each request type. 
- there was UTF8 issues, that have been fixed.

We can fix all this issues. 

The first one would take time from OpenNebula, I guess we can maintain a separate set of XSDs with the additional elements that we find missing, and open pull requests in parallel. We could even implement an "strict" mode that uses the XSDs as distributed by OpenNebula. 

To fix the second, we will need to compile separate bindings for each request type, implement a registry and use the binding that matches the request/response type.

**Comment by rvalle** [comment]
The author of PyXB suggested that we look into generateDS as an alternative.
It is a similar module but works in a different way, it is more relaxed in terms of validation, and it is also possible to extend the generated bindings.
I think this might fix all the above issues.

**Comment by rvalle** [comment]
@Madko @marcindulak 
I have migrated pyone from PyXB to GenerateDS, I have pushed it to the branch:

https://github.com/OpenNebula/addon-pyone/tree/generateDS

It seems to be working very well, generateDS is tolerant to all this errors and allows for better customization of the generated types. This allows to implement #11.

It is currently working in Python 2.7, but still complaining here and there in Python 3.6. Once I get it working will release it.

if you have a chance, test a bit with it.

**Comment by marcindulak** [comment]
I've tried GenerateDS https://github.com/OpenNebula/addon-pyone/issues/12

**Comment by Madko** [comment]
I've been able to get all my VM info from my test lab #1 (about 600VM definitions). I will try to test that on a bigger environment. But so far, so good ! great work

**Comment by rvalle** [comment]
this should be fixed for now, thou it would not surprise me if in your bigger environment you find something else failing.

**Comment by Madko** [comment]
Nope, everything works fine :) thanks!

**Comment by rvalle** [comment]
great!

**Comment by rvalle** [comment]
Ok, I notice that the XSDs are being updated in https://github.com/OpenNebula/one/issues/1821
Lets leave this issue open to keep track of it.
